runs:
  using: "composite"
  steps:
    - name: Build project
      shell: bash
      run: xcodebuild clean build -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDK -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
