runs:
  using: "composite"
  steps:
    - name: Setup Path Filter task and Execute
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          md: ['CHANGELOG.md']
          txt: ['sdk-version.txt']
          h: ['CleverTapSDK/CleverTapBuildInfo.h']

    - name: FAIL if mandatory files are not changed
      if: ${{ steps.filter.outputs.md == 'false' || steps.filter.outputs.podspec == 'false' || steps.filter.outputs.h == 'false'}}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Mandatory markdown files were not changed')
