runs:
  using: "composite"
  steps:
     - name: Validate PR Description
       shell: bash
       env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
       run: |
          if [[ -z "$PR_DESCRIPTION" ]]; then
            echo "::warning ::Invalid PR Description format. Please add valid description."
          fi
